### PR TITLE
Allow array of files

### PR DESCRIPTION
**Pull request by SimenB**
@RyanEwen Thoughts on this?

### CODE REVIEW

**Comment by RyanEwen** [comment]
I will be taking a look and trying it out on Monday, thanks! :D

**Comment by SimenB** [comment]
The order in the html file will actually be the reverse of what's passed in, I'll juat reverse it

**Comment by RyanEwen** [comment]
I tried to test this but when I install it via `npm install SimenB/add-asset-html-webpack-plugin#multiple-files` command I only end up getting the README.md, LICENSE, and package.json files. I'm somewhat new to npm.. any tips?

**Comment by SimenB** [comment]
You have to clone the repo and `npm link` it locally

On Mon, 30 May 2016, 17:12 Ryan Ewen, <notifications@github.com> wrote:

> I tried to test this but when I install it via npm install
> SimenB/add-asset-html-webpack-plugin#multiple-files command I only end up
> getting the README.md, LICENSE, and package.json files. I'm somewhat new to
> npm.. any tips?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SimenB/add-asset-html-webpack-plugin/pull/6#issuecomment-222512239>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABVvisgmzBSZOI6Emgt6bJ_zdvmxbTQ4ks5qGv5tgaJpZM4IpBSE>
> .
>
-- 

--
Simen Bekkhus

**Comment by RyanEwen** [comment]
I am getting an error trying to use this:

```
Unhandled rejection TypeError: Path must be a string. Received [ '/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/dist/vuewebThirdPartyDll.bundle.js',
  '/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/dist/vuewebFirstPartyDll.bundle.js' ]
  at assertPath (path.js:7:11)
  at Object.resolve (path.js:1146:7)
  at HtmlWebpackPlugin.addFileToAssets (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/html-webpack-plugin/index.js:290:19)
  at addFileToAssets (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/index.js:42:32)
  at /home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/index.js:69:20
  at tryCatcher (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/node_modules/bluebird/js/release/util.js:16:23)
  at Object.gotValue (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/node_modules/bluebird/js/release/reduce.js:145:18)
  at Object.gotAccum (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/node_modules/bluebird/js/release/reduce.js:134:25)
  at Object.tryCatcher (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/node_modules/bluebird/js/release/util.js:16:23)
  at Promise._settlePromiseFromHandler (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/node_modules/bluebird/js/release/promise.js:502:31)
  at Promise._settlePromise (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/node_modules/bluebird/js/release/promise.js:559:18)
  at Promise._settlePromiseCtx (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/node_modules/bluebird/js/release/promise.js:596:10)
  at Async._drainQueue (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/node_modules/bluebird/js/release/async.js:143:12)
  at Async._drainQueues (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/node_modules/bluebird/js/release/async.js:148:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/home/rewen/vueweb/vueweb-launcher/node_modules/vueweb-libs/node_modules/add-asset-html-webpack-plugin/node_modules/bluebird/js/release/async.js:17:14)
  at tryOnImmediate (timers.js:543:15)
  at processImmediate [as _immediateCallback] (timers.js:523:5)
```

**Comment by RyanEwen** [comment]
Never mind, I misunderstood the change to the readme and was passing filename as an array.

It works when I pass in an array of objects to the plugin. :)

**Comment by SimenB** [comment]
Sweet! 

I'll release it tonight

**Comment by SimenB** [comment]
Any idea on how to formulate the sentence? As it wasn't obvious, might be a good idea to rephrase

**Comment by SimenB** [comment]
@RyanEwen I just merged it, with a small change. If you can think of a better wy to phrase it, don't hesitate to open a PR!

**Comment by SimenB** [comment]
Published as `0.2.0` 😄

**Comment by RyanEwen** [comment]
The docs are clear enough, it was just me failing to properly read them :)

Thanks!

**Pull request merged**
