### PR TITLE
fix: add support for html-webpack-plugin@4

### LINKED ISSUE #132: after updating to html-webpack-plugin@4.0.0-alpha, it turns to undefined
```js
config.plugins.push(
  new AddAssetHtmlPlugin([
    {
      hash: true,
      filepath: require.resolve(PATH.SOURCE_PATH + '/js/vendor/fabric.min.js'),
      includeSourcemap: false
    }
  ]
)
```

html-webpack-plugin@3.0.6
```html
<script type="text/javascript" src="/fabric.min.js?bf4b231c259745703b2b">
```

html-webpack-plugin@4.0.0-alpha
```html
<script type="text/javascript" src="undefined">
```

### PR DESCRIPTION
**Pull request by SimenB**
Fixes #132 

@jantimon thoughts on this? Seems to work fine (run `yarn example && open example/dist/index.html` to see a working example with dll and source map).

---

I have to admit it's more than 2 years since I did anything with Webpack so I haven't really followed along. So any pointers would be appreciated 🙂

### CODE REVIEW

**Comment by jantimon** [comment]
Wow cool will take a look asap :)

**Comment by jantimon** [comment]
hey @SimenB it looks already really good 👍

**Comment by SimenB** [comment]
Awesome, thanks for taking a look!

**Pull request merged**
