### PR TITLE
Make webpack 4 compatible

### PR DESCRIPTION
**Pull request by macisi**
Now the plugin works fine with webpack@4.0.0 and html-webpack-plugin@3.0.4. 😃

### CODE REVIEW

**Comment by SimenB** [comment]
Thanks! I'll make some more tweaks before releasing 3.0.0 🙂

**Comment by JounQin** [comment]
`Error: Plugin could not be registered at 'html-webpack-plugin-before-html-generation'.` on webpack 4.1.0, html-webpack-plugin 3.0.6

**Comment by SimenB** [comment]
Oh, I didn't know that! Makes sense though. Mind sending a PR specifying that in the readme? 🙂

**Comment by JounQin** [comment]
@SimenB Please review #103 .

**Pull request merged**
