### PR TITLE
Add outputPath option

### PR DESCRIPTION
**Pull request by wadahiro**
Currently, the asset file is wrtten to webpack `output.path` directory always. To write the file into sub directory,   I added `outputPath` option into AddAssetHtmlPlugin options. 

### `webpack.config.js`
```js:
module.exports = {
  entry: ['babel-polyfill', './src/script/index.jsx'],
  output: {
    path: path.join(__dirname, './build'),
    publicPath: '',
    filename: 'app.js'
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html'
    }),
    new AddAssetHtmlPlugin({
      filename: require.resolve('./build/assets/vendor.js'),
      publicPath: 'assets',
      outputPath: 'assets',
      includeSourcemap: true
    })
  ],
  ...
```

### The generated files

```
build
├─app.js
├─assets
│  ├─vendor.js
│  └─vendor.js.map
└─index.html
```

### The generated HTML

```html

<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My App</title>
  </head>
  <body>
    <div id="app"></div>

  <script type="text/javascript" src="assets/vendor.js?d7a424bd84a886d21d82"></script><script type="text/javascript" src="app.js?02910af8479e3f4271e6"></script></body>
</html>

```

### CODE REVIEW

**Comment by SimenB** [comment]
Thanks again for a PR! As we're starting to get a good bit of logic here, I'll write some tests for the plugin today. Then when we're sure it works as expected, we can merge this 😄

**Comment by SimenB** [comment]
@wadahiro See #17 for tests. I'll wrap it up ASAP, but as I'm on holiday, it might be a couple of days 😄 If you wanna help out, feel free.

**Comment by SimenB** [comment]
@wadahiro I merged the tests. If you'd rebase on master and add a test for your change, that'd be great 😄 

THe build will fail if coverage is not 100%, use `npm run cover` to check what you have

**Comment by wadahiro** [comment]
@SimenB ok. I'll rebase and add a test!

**Comment by SimenB** [comment]
Great, thanks! I'm on a trip right now, will release 1.0.0 tonight. Thanks for all the PRs :smile:

**Comment by SimenB** [comment]
@wadahiro published as 1.0.0

**Pull request merged**
